AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Hello World AWS Lambda and Amazon API Gateway REST API

  Sample AWS SAM template to create a simple Lambda function connected to a REST API.

Parameters:
  SecretArn:
    Type: String
    Default: arn:aws:secretsmanager:us-west-1:268556604879:secret:OPENAI_API_KEY_SECRET-CUsnOn

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180
    Environment:
      Variables:
        OPENAI_API_KEY_ARN: !Ref SecretArn

Resources:
  SharedHelpersLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-helpers
      Description: Common helper functions for Lambdas
      ContentUri: layers/shared/
      CompatibleRuntimes:
        - python3.12

  GenerateTOCFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: generate_toc/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Layers:
        - !Ref SharedHelpersLayer
        - arn:aws:lambda:us-west-1:997803712105:layer:AWS-Parameters-and-Secrets-Lambda-Extension:18
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretArn
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - http://localhost:5173
            - https://main.d2xyu58sfma11c.amplifyapp.com
          AllowMethods:
            - POST
          AllowHeaders:
            - "*"
          MaxAge: 0
          AllowCredentials: false

  GenerateArticleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: generate_article/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Layers:
        - !Ref SharedHelpersLayer
        - arn:aws:lambda:us-west-1:997803712105:layer:AWS-Parameters-and-Secrets-Lambda-Extension:18
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretArn
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - http://localhost:5173
            - https://main.d2xyu58sfma11c.amplifyapp.com
          AllowMethods:
            - POST
          AllowHeaders:
            - "*"
          MaxAge: 0
          AllowCredentials: false

  GenerateProblemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: generate_problems/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Layers:
        - !Ref SharedHelpersLayer
        - arn:aws:lambda:us-west-1:997803712105:layer:AWS-Parameters-and-Secrets-Lambda-Extension:18
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretArn
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - http://localhost:5173
            - https://main.d2xyu58sfma11c.amplifyapp.com
          AllowMethods:
            - POST
          AllowHeaders:
            - "*"
          MaxAge: 0
          AllowCredentials: false

  GenerateFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: generate_feedback/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Layers:
        - !Ref SharedHelpersLayer
        - arn:aws:lambda:us-west-1:997803712105:layer:AWS-Parameters-and-Secrets-Lambda-Extension:18
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretArn
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - http://localhost:5173
            - https://main.d2xyu58sfma11c.amplifyapp.com
          AllowMethods:
            - POST
          AllowHeaders:
            - "*"
          MaxAge: 0
          AllowCredentials: false

Outputs:
  GenerateTOCFunctionUrl:
    Description: "Generate TOC Lambda Function URL Endpoint"
    Value:
      Fn::GetAtt: GenerateTOCFunctionUrl.FunctionUrl

  GenerateArticleFunctionUrl:
    Description: "Generate Article Lambda Function URL Endpoint"
    Value:
      Fn::GetAtt: GenerateArticleFunctionUrl.FunctionUrl

  GenerateProblemsFunctionUrl:
    Description: "Generate Problems Lambda Function URL Endpoint"
    Value:
      Fn::GetAtt: GenerateProblemsFunctionUrl.FunctionUrl

  GenerateFeedbackFunctionUrl:
    Description: "Generate Feedback Lambda Function URL Endpoint"
    Value:
      Fn::GetAtt: GenerateFeedbackFunctionUrl.FunctionUrl
